project_id = "obkfkygjisxvgrmclhnb"

[functions.send-confirmation-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
